export const APP_LOAD = "APP_LOAD";
export const REDIRECT = "REDIRECT";
export const LOGIN = "LOGIN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const LOGOUT = "LOGOUT";
export const CLEAR_LOGOUT = "CLEAR_LOGOUT";
export const REGISTER = "REGISTER";
export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const REGISTER_PAGE_UNLOADED = "REGISTER_PAGE_UNLOADED";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const CURRENT_VIEW = "CURRENT_VIEW";
export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";
export const PLAN_FETCH = "PLAN_FETCH";
export const SUBSCRIBE_PLAN = "SUBSCRIBE_PLAN";
export const ADMIN_PLAN_FETCH = "ADMIN_PLAN_FETCH";
export const PLAN_FEATURES = "PLAN_FEATURES";
export const PLAN_DETAIL = "PLAN_DETAIL";
export const ADD_PLAN = "ADD_PLAN";
export const ADD_FEATURE = "ADD_FEATURE";
export const EDIT_FEATURE = "EDIT_FEATURE";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const ADMIN_FEATURE_FETCH = "ADMIN_FEATURE_FETCH";
export const CLEAR_PLAN_MESSAGE = "CLEAR_PLAN_MESSAGE";
export const ADMIN_PLAN_DETAIL = "ADMIN_PLAN_DETAIL";
export const ADMIN_EDIT_PLAN = "ADMIN_EDIT_PLAN";
export const ADMIN_PLAN_FEATURE_FETCH = "ADMIN_PLAN_FEATURE_FETCH";
export const SEND_QUERY = "SEND_QUERY";
export const CLEAR_PLAN_DATA = "CLEAR_PLAN_DATA";
export const FEATCH_CLUB_REQUEST = "CLEAR_PLAN_DATA";
export const ACCEPT_CLUB_REQUEST = "ACCEPT_CLUB_REQUEST";
export const CLEAR_REQUEST_MESSAGE = "CLEAR_REQUEST_MESSAGE";
export const DECLINE_CLUB_REQUEST = "DECLINE_CLUB_REQUEST";
export const ADMIN_CLUB_FETCH = "ADMIN_CLUB_FETCH";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const ADMIN_DASHBOARD_DATA = "ADMIN_DASHBOARD_DATA";
export const AFTER_SUCCESS = "AFTER_SUCCESS";
export const RECENT_CLUB_REQUEST = "RECENT_CLUB_REQUEST";
export const FEATCH_CLUB_BY_ID = "FEATCH_CLUB_BY_ID";
export const ADMIN_PROFILE_UPDATE = "ADMIN_PROFILE_UPDATE";
export const ADMIN_CLEAR_MESSAGES = "ADMIN_CLEAR_MESSAGES";
export const STAFF_DETAIL = "STAFF_DETAIL";
export const DELETE_CLUB = "DELETE_CLUB";
export const OWNER_DASHBOARD_DATA = "OWNER_DASHBOARD_DATA";
export const PAGE_ATTR = "PAGE_ATTR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const GET_SETTINGS = "GET_SETTINGS";
/*Admin*/
export const SAVE_PROMOTION_SETTING = "SAVE_PROMOTION_SETTING";
export const GET_PROMOTION_SETTING = "GET_PROMOTION_SETTING";
export const FETCH_ADMIN_PROMOTIONS = "FETCH_ADMIN_PROMOTIONS";
export const FETCH_QUERIES = "FETCH_QUERIES";
export const FETCH_QUERY = "FETCH_QUERY";
export const RESOLVE_QUERY = "RESOLVE_QUERY";
export const ADMIN_EARNING_DATA = "ADMIN_EARNING_DATA";
export const ADMIN_CHANGE_PASSWORD = "ADMIN_CHANGE_PASSWORD";
export const ADMIN_SAVE_SETTINGS = "ADMIN_SAVE_SETTINGS";
export const ADMIN_GET_NOTIFICATION_STATUS = "ADMIN_GET_NOTIFICATION_STATUS";
export const PROMOTIONS_BY_CLUB = "PROMOTIONS_BY_CLUB";
export const ADMIN_PAYMENTS_FETCH = "ADMIN_PAYMENTS_FETCH";
export const FEATCH_PAYMENT_BY_ID = "FEATCH_PAYMENT_BY_ID";
/*owner*/
export const CONTACT_BY_OWNER = "CONTACT_BY_OWNER";
export const SAVE_STRIPE_ACCOUNT = "SAVE_STRIPE_ACCOUNT";
export const CHECK_STRIPE_ACCOUNT = "CHECK_STRIPE_ACCOUNT";
export const LOGIN_STRIPE = "LOGIN_STRIPE";
export const SETUP_STRIPE = "SETUP_STRIPE";
export const FETCH_STRIPE_BANK_DETAILS = "FETCH_STRIPE_BANK_DETAILS";
export const EDIT_STRIPE_BANK_DETAILS = "EDIT_STRIPE_BANK_DETAILS";
export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";
export const OWNER_SUBSCRIBE_PLAN = "OWNER_SUBSCRIBE_PLAN";
export const OWNER_PROFILE_UPDATE = "OWNER_PROFILE_UPDATE";
export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";
export const OWNER_EARNING_DATA = "OWNER_EARNING_DATA";
export const FETCH_ORDERS_EARNINGS = "FETCH_ORDERS_EARNINGS";
export const FETCH_EVENTS_EARNINGS = "FETCH_EVENTS_EARNINGS";
/*Manager*/
export const ADD_MANAGER = "ADD_MANAGER";
export const DELETE_MANAGER = "DELETE_MANAGER";
export const GET_MANAGERS = "GET_MANAGERS";
export const FETCH_MANAGER_DETAIL = "FETCH_MANAGER_DETAIL";
export const UPDATE_MANAGER = "UPDATE_MANAGER";
export const MANGER_PROFILE_UPDATE = "MANGER_PROFILE_UPDATE";
export const MANGER_CHANGE_PASSWORD = "MANGER_CHANGE_PASSWORD";
/*Promotion*/
export const FETCH_PROMOTIONS = "FETCH_PROMOTIONS";
export const CREATE_PROMOTION = "CREATE_PROMOTION";
export const FETCH_PROMOTION_DETAIL = "FETCH_PROMOTION_DETAIL";
/*Event*/
export const FETCH_EVENTS = "FETCH_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_IMAGE = "DELETE_EVENT_IMAGE";
export const FETCH_EVENT_DETAIL = "FETCH_EVENT_DETAIL";
/*Bookings*/
export const GET_BOOKINGS = "GET_BOOKINGS";
export const ASSIGN_TABLE = "ASSIGN_TABLE";
/*Menu*/
export const FETCH_MENU = "FETCH_MENU";
export const GET_MENU_DETAIL = "GET_MENU_DETAIL";
export const ADD_MENU = "ADD_MENU";
export const UPDATE_MENU = "UPDATE_MENU";
export const DELETE_MENU = "DELETE_MENU";
/*Staff*/
export const GET_STAFF = "GET_STAFF";
export const AFTER_STAFF_SAVE = "AFTER_STAFF_SAVE";
export const SAVE_STAFF = "SAVE_STAFF";
export const STAFF_UPDATE = "STAFF_UPDATE";
export const DELETE_STAFF = "DELETE_STAFF";

/*Orders*/
export const GET_CURRENT_ORDERS = "GET_CURRENT_ORDERS";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const SET_ORDER_STATUS = "SET_ORDER_STATUS";
export const GET_ORDER_BILL = "GET_ORDER_BILL";
export const GENERATE_ORDER_INVOICE = "GENERATE_ORDER_INVOICE";

/*Notification*/
export const GET_NOTIFICATION_COUNT = "GET_NOTIFICATION_COUNT";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
